### ISSUE TITLE
Data Import Needs a Refactor to Abstract Concerns

### ISSUE THREAD

**Issue by tonyyates** [open-ods/open-ods#16]
The data import routing needs to be refactored so it is testable and also separates concerns.

**Comment by mattstibbs** [comment]
@tonyyates Agreed. 

I have been thinking about this a bit and there are a couple of things that need addressing:

1. Creating Models for the different data types so that we can ensure that consistency is there, and then refactoring the code to use those models wherever the data is touched.

2. Potentially creating a new import package (hence empty openods-import package) which potentially uses an ORM (like SqlAlchemy) to handle the data. I have been hand-rolling database schema migrations at the moment, but it's not the most sustainable approach.

Might be worth tackling this one in stages?

**Comment by tonyyates** [comment]
Agree on those points. Just working through the code to make it abstract
from the database connection and separate the concerns initially then I
will add the tasks to make it how we want it to be.

T

**Comment by mattstibbs** [comment]
Cool - take a look at the main openods-api package as I have separated the DB connection out in that at least. I also have some code in blockbuster-server to handle connection pooling but not sure we need that yet.

**Comment by tonyyates** [comment]
will do, thanks
