### ISSUE TITLE
Create docker instance

### ISSUE THREAD

**Issue by TimCoates** [open-ods/open-ods#34]
It would be good to provide a dockerfile for the server, and one for the database server.

**Comment by mattstibbs** [comment]
@TimCoates good idea - don't have a lot of experience with docker so will have to learn it before can add it unfortunately

We do have an issue open to add a Vagrantfile which I have done before so that might help in the interim

**Comment by paulfurley** [comment]
Does this supercede #11 or do you want both?

**Comment by mattstibbs** [comment]
@paulfurley to be honest I think the main need we're trying to meet here is an easy way for people to spin up a local copy either for playing around with or as a dev environment

Vagrant was my first port of call simply because I've used it before - I'm still not completely up to speed with docker.

I think docker would be a good place to start.

**Comment by mattstibbs** [comment]
@paulfurley to be honest I think the main need we're trying to meet here is an easy way for people to spin up a local copy either for playing around with or as a dev environment

Vagrant was my first port of call simply because I've used it before - I'm still not completely up to speed with docker.

I think docker would be a good place to start.

**Comment by mattstibbs** [comment]
@ahatherly assigned this issue to you as you're covering off with your work anyway

**Comment by mattstibbs** [comment]
Dockerfile now added.
